version: '3.8'
services:
  go-app:
    build: .
    container_name: chat-histories-service
    ports:
      - "80:80"
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go elastic.go rabbitmq.go
